##///
##||| FINAL.PY TITANIUM
##||| Change list:
##||| * Adjusted door coordinates so that the final door actually closes instead of leaving a huge gap in the middle.
##||| * 
##||| * 
##\\\ 

# Item configuration script
# Script generated by LED: May 17 1999 15:40:27


# Script with 2 Items.

#o=Bladex.CreateEntity("PuertaFin0","PuertaFernando",90551.818845,-11871.737814,195045.357000)      Original one
o=Bladex.CreateEntity("PuertaFin0","PuertaFernando",90799.356000,-11900.780000,195045.357000)
o.Scale=1.000000
o.Orientation=0.533660,0.533660,0.463904,-0.463904
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


#o=Bladex.CreateEntity("PuertaFin1","PuertaFernando",98230.671460,-11913.530670,195087.409000)      Original one
o=Bladex.CreateEntity("PuertaFin1","PuertaFernando",97874.461000,-11900.776000,195087.409000)
o.Scale=1.000000
o.Orientation=0.454519,0.454519,0.541675,-0.541675
#o.NodesOrientation=?  En la siguiente versión
#o.Scripts=?  En la siguiente versión


