#####                                            ######
# Config functions for (some) of your Titanium needs  #
#####                                            ######

import sys
import os

#Default values
DodgeFix=1




#Saves Titanium specific settings
def SaveTitaniumCfg():
    cfgfile=open('../../Config/Titanium/TiCfg.py','w')
    cfgfile.write('\n# Whenever making changes to this config, game MUST be restarted!\n')    
    cfgfile.write('\n# Autogenerated Titanium config file\n\n\n')
    cfgfile.write('TitaniumSettings={}\n')
    cfgfile.write('TitaniumSettings["DodgeFix"]='+`DodgeFix`+'\n')
    cfgfile.write('\n# Have fun!!.\n\n\n')
    cfgfile.close()

    print "Titanium settings saved."

if not os.path.exists('../../Config/Titanium/TiCfg.py'):
    try:
        os.mkdir("../../Config/Titanium")
    except:
        pass
    SaveTitaniumCfg()

# Reads a specific Titanium setting
def TitaniumSetting(param):
    sys.path.append("../../Config/Titanium")
    from TiCfg import TitaniumSettings
    return TitaniumSettings[param]
    sys.path.remove("../../Config/Titanium")